apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-env
      env: development
  template:
    metadata:
      labels:
        app: k8s-env
        env: development
    spec:
      containers:
      - name: display-env
        image: pythonincontainers/k8s-env:v1.0
        ports:
        - containerPort: 5000
        env:
          - name: Environment
            value: Development
