apiVersion: v1
kind: Service
metadata:
  name: node-port
spec:
  type: NodePort
  selector:
    app: k8s-env
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30100 # must be in range 30000-32767
